spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/muckja?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 36391964a@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


jwt:
  secret: ${SECRET}
  access_exp: ${ACCESS_EXP}